#!/bin/bash

INSTALL_DIR=${1:-$(pwd)}

echo "Installing into $INSTALL_DIR"

mvn clean install
mvn -Dmdep.outputFile=cp.txt -Dmdep.includeScope=runtime dependency:build-classpath

MEM=$(cat /proc/meminfo | grep MemTotal | sed s/^MemTotal:\\\s*\\\|\\\s\\+[^\\\s]*$//g)
MEM=$(($MEM/2/1024/1024))

cat << EOF > bigcat
#!/bin/bash

JAR="\$HOME/.m2/repository/sc/fiji/bigcat/0.0.4-SNAPSHOT/bigcat-0.0.4-SNAPSHOT.jar"
java \\
  -Xmx${MEM}g \\
  -XX:+UseConcMarkSweepGC \\
  -cp "\$JAR:$(cat cp.txt)" \\
  bdv.bigcat.BigCat "\$@"
EOF

chmod a+x bigcat
rm cp.txt

mkdir -p $INSTALL_DIR
mv -f bigcat $INSTALL_DIR/

